server:
  port: 9002

spring:
  application:
    name: app-b
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/sso-poc
          jwk-set-uri: http://localhost:8080/realms/sso-poc/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: app-b
            authorization-grant-type: authorization_code
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/sso-poc
            user-name-attribute: preferred_username

logging:
  level:
    org.springframework.security: DEBUG
    com.example.sso: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
      cors:
        allowed-origins: http://localhost:3002
        allowed-methods: GET,POST,PUT,DELETE
        allowed-headers: "*"
